### ISSUE TITLE
init.lua file - Remove error function

### ISSUE THREAD

**Issue by ghost** [doqedev/repldbservice#1]
<a name="why"></a>
### The problem
The error function on line 64 should be removed because [error() stops the script and requires the user to start game session again](https://devforum.roblox.com/t/when-should-i-use-the-error-command/744681) to restart the script. 

### Solution
Use warn() instead, it is more visible in the developer console and is much favoured by developers than [error()](#why)

**Comment by doqedev** [comment]
Done! [The commit is here.](https://github.com/doqedev/repldbservice/commit/2d3f849fc9b3ef7cd16308a03187c69c2c121e48), will update wally dependency later

**Comment by ghost** [comment]
Might want to remove ,5 from the warn function as it will not do anything

**Comment by doqedev** [comment]
Noticed that, removed it and published to wally.
